version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.test.ir'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.test.ir'
        # Add any other gitlab.rb configuration here, each on its own line
        # Registry
        # GITLAB_REGISTRY_ENABLED: 'true'
        # GITLAB_REGISTRY_HOST: 'registry.test.ir'
        # GITLAB_REGISTRY_PORT: '443'
        # GITLAB_REGISTRY_API_URL: 'registry.test.ir'
        # GITLAB_REGISTRY_KEY_PATH: '/certs/registry.key'
    ports:
      - '81:80'
      - '444:443'
      - '22:22'      
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'
